CREATE TABLE IF NOT EXISTS tweets (
	tweet_id INTEGER PRIMARY KEY AUTOINCREMENT,
	tweet_text TEXT NOT NULL,
	created_at TEXT NOT NULL, 
	user_id INTEGER NOT NULL,
	screen_name TEXT NOT NULL,
	name TEXT DEFAULT NULL,
	profile_image_url TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS tweet_mentions (
	tweet_mention_id INTEGER PRIMARY KEY AUTOINCREMENT,
	source_user_id INTEGER NOT NULL,
	target_user_id INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS tweet_tags (
	tweet_tag_id INTEGER PRIMARY KEY AUTOINCREMENT,
	tag TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tweet_urls (
	tweet_url_id INTEGER PRIMARY KEY AUTOINCREMENT,
	url TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
	user_id INTEGER PRIMARY KEY AUTOINCREMENT,
	screen_name TEXT NOT NULL,
	name TEXT DEFAULT NULL,
	profile_image_url TEXT DEFAULT NULL,
	email TEXT DEFAULT NULL,
	url TEXT DEFAULT NULL,
	description TEXT DEFAULT NULL,
	created_at TEXT NOT NULL,
	followers_count INTEGER DEFAULT NULL,
	friends_count INTEGER DEFAULT NULL
)